[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]

# curves
curve25519-dalek = {version = "4.1.3", features = ["rand_core", "digest"] }
p256 = { version = "0.13.2", features = ["arithmetic", "std", "hash2curve"] }
# elgamal_p256 = { path = "deps/elgamal_p256", optional = true }
# num = { version "0.4.0", optional = true }
# base64 = "0.22.1"

# hashing
sha3 = "0.10"

# rng
rand = { version = "0.8", features = ["std"] }

# signatures
ed25519-dalek = {version = "2.2.0", features=["rand_core"] }

# misc
thiserror = "1.0.50"
rayon = { version = "1.10.0", optional = true }
cfg-if = "1.0.1"

# wasm
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
web-time = "1.1.0"
js-sys = "0.3"

# serialization
vser_derive = { path = "./macros/vser_derive" }
#serde = { version = "1.0.219", features=["derive"], optional = true }
#bincode = { version = "2.0.1", features=["serde"], optional = true }
serde = { version = "1.0.219", features=["derive"] }
bincode = { version = "2.0.1", features=["serde"] }

custom_warning_macro = { path = "./macros/custom_warning_macro" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
test = true
name = "crypto"

[features]
default = ["client", "server"]
server = ["dep:rayon"]
client = []
custom-warnings = ["custom_warning_macro/on"]
# serde = ["dep:serde", "dep:bincode"]
# pfec = ["dep:elgamal_p256", "dep:num"]

# [package.metadata.wasm-pack.profile.release] 
# wasm-opt = ["-O", "--enable-bulk-memory", "--enable-mutable-globals", "--enable-reference-types"]

[[bench]]
name = "large_vector"
harness = true

[[bench]]
name = "shuffle"
harness = true

[dev-dependencies]
serde = { version = "1.0.219", features=["derive"] }
bincode = { version = "2.0.1", features=["serde"] }
assertions = "0.1.0"


